name = "cloudflare"
type = "javascript"
account_id = "b0f83c06d5bfc8d6ef599959707dac36"
workers_dev = true
route = ""
zone_id = ""

[env.production]
# The ID of your domain you're deploying to
zone_id = "b1eb90cc3d90644568f56617fb12dd89"
# The route pattern your Workers application will be served at
route = "michaelyh.com/cloudflare"
